apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web
  namespace: flask-prod
  labels:
    app: flask-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-web
  template:
    metadata:
      labels:
        app: flask-web
      annotations:
        # --- MUDANÇA 1: Comentamos o SigNoz para evitar conflito ---
        # instrumentation.opentelemetry.io/inject-python: "signoz/signoz-instrumentation"
    spec:
      containers:
        - name: flask-web
          # --- MUDANÇA 2: Usamos a imagem nova com o JS do Grafana ---
          image: ghcr.io/amsatnaf/flask-web:v-grafana-01
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          # --- MUDANÇA 3: Variáveis apontando para o Alloy (Agente Grafana) ---
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://grafana-k8s-monitoring-alloy.monitoring.svc.cluster.local:4317"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "grpc"
          - name: OTEL_SERVICE_NAME
            value: "flask-web-loja"
            
          # --- Variáveis do Banco (Mantidas) ---
          - name: DB_HOST
            value: "34.44.72.27"
          - name: DB_NAME
            value: "loja_rum"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-gcp-creds
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: mysql-gcp-creds
                key: DB_PASS
