apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-grafana-loja
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"  # opcional para TLS
spec:
  ingressClassName: traefik
  rules:
    - host: flask.grafana.129.213.28.76.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-grafana-loja
                port:
                  number: 80
# tls:
#   - hosts:
#       - flask.prod.129.213.28.76.sslip.io
#     secretName: flask-grafana-tls
