apiVersion: v1
kind: Service
metadata:
  name: flask-grafana-loja
  labels:
    app: flask-grafana-loja
spec:
  type: ClusterIP
  selector:
    app: flask-grafana-loja
  ports:
    - name: web       # <--- MUDAMOS DE 'http' PARA 'web'
      port: 80
      targetPort: 8080
      protocol: TCP
