
apiVersion: v1
kind: Service
metadata:
  name: flask-web
  namespace: flask-prod
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: flask-web
  ports:
    - name: http
      port: 80
      targetPort: 8080

